# Generated by Django 4.0.3 on 2022-04-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=80)),
                ('lecturer', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('projectfile', models.FileField(default=0, upload_to='media/')),
            ],
        ),
    ]
