# Generated by Django 4.0.4 on 2022-04-27 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='projectfile',
            field=models.FileField(default=0, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
